export const fromFreemind = {
    'idea': 'Idea',
    'help': 'Question',
    'yes': 'Important',
    'messagebox_warning': 'Warning',
    'stop-sign': 'Stop',
    'closed': 'No Entry',
    'info': 'info',
    'button_ok': 'OK',
    'button_cancel': 'Not OK',
    'full-1': 'Priority 1',
    'full-2': 'Priority 2',
    'full-3': 'Priority 3',
    'full-4': 'Priority 4',
    'full-5': 'Priority 5',
    'full-6': 'Priority 6',
    'full-7': 'Priority 7',
    'full-8': 'Priority 8',
    'full-9': 'Priority 9',
    'full-0': 'Priority 0',
    'stop': 'Red Traffic Light',
    'prepare': 'Yellow Traffic Light',
    'go': 'Green Traffic Light',
    'back': 'Back',
    'forward': 'Forward',
    'up': 'Up',
    'down': 'Down',
    'attach': 'Look here',
    'ksmiletris': 'I am happy',
    'smiley-neutral': 'No Mind',
    'smiley-oh': 'Surprising',
    'smiley-angry': 'Angry',
    'smily_bad': 'I am not amused',
    'clanbomber': 'Dangerous',
    'desktop_new': 'Do not forget',
    'gohome': 'Home',
    'folder': 'Folder',
    'korn': 'Mailbox',
    'Mail': 'Mail',
    'kmail': 'E-Mail',
    'list': 'List',
    'edit': 'Refine',
    'kaddressbook': 'Phone',
    'knotify': 'Music',
    'password': 'Key',
    'pencil': 'To be refined',
    'wizard': 'Magic',
    'xmag': 'To be discussed',
    'bell': 'Remember',
    'bookmark': 'Excellent',
    'penguin': 'Linux',
    'licq': 'Nice',
    'freemind_butterfly': 'FreeMind',
    'broken-line': 'Broken',
    'calendar': 'Date',
    'clock': 'Time',
    'hourglass': 'Waiting',
    'launch': 'Launch',
    'flag-black': 'Black Flag',
    'flag-blue': 'Blue Flag',
    'flag-green': 'Green Flag',
    'flag-orange': 'Orange Flag',
    'flag-pink': 'Pink Flag',
    'flag': 'Red Flag',
    'flag-yellow': 'Yellow Flag',
    'family': 'Family',
    'female1': 'Female1',
    'female2': 'Female2',
    'male1': 'Male1',
    'male2': 'Male2',
    'fema': 'Females',
    'group': 'Group',
}


export const toFreemind = {
    Idea: 'idea',
    Question: 'help',
    Important: 'yes',
    Warning: 'messagebox_warning',
    Stop: 'stop-sign',
    'No Entry': 'closed',
    info: 'info',
    OK: 'button_ok',
    'Not OK': 'button_cancel',
    'Priority 1': 'full-1',
    'Priority 2': 'full-2',
    'Priority 3': 'full-3',
    'Priority 4': 'full-4',
    'Priority 5': 'full-5',
    'Priority 6': 'full-6',
    'Priority 7': 'full-7',
    'Priority 8': 'full-8',
    'Priority 9': 'full-9',
    'Priority 0': 'full-0',
    'Red Traffic Light': 'stop',
    'Yellow Traffic Light': 'prepare',
    'Green Traffic Light': 'go',
    Back: 'back',
    Forward: 'forward',
    Up: 'up',
    Down: 'down',
    'Look here': 'attach',
    'I am happy': 'ksmiletris',
    'No Mind': 'smiley-neutral',
    Surprising: 'smiley-oh',
    Angry: 'smiley-angry',
    'I am not amused': 'smily_bad',
    Dangerous: 'clanbomber',
    'Do not forget': 'desktop_new',
    Home: 'gohome',
    Folder: 'folder',
    Mailbox: 'korn',
    Mail: 'Mail',
    'E-Mail': 'kmail',
    List: 'list',
    Refine: 'edit',
    Phone: 'kaddressbook',
    Music: 'knotify',
    Key: 'password',
    'To be refined': 'pencil',
    Magic: 'wizard',
    'To be discussed': 'xmag',
    Remember: 'bell',
    Excellent: 'bookmark',
    Linux: 'penguin',
    Nice: 'licq',
    FreeMind: 'freemind_butterfly',
    Broken: 'broken-line',
    Date: 'calendar',
    Time: 'clock',
    Waiting: 'hourglass',
    Launch: 'launch',
    'Black Flag': 'flag-black',
    'Blue Flag': 'flag-blue',
    'Green Flag': 'flag-green',
    'Orange Flag': 'flag-orange',
    'Pink Flag': 'flag-pink',
    'Red Flag': 'flag',
    'Yellow Flag': 'flag-yellow',
    Family: 'family',
    Female1: 'female1',
    Female2: 'female2',
    Male1: 'male1',
    Male2: 'male2',
    Females: 'fema',
    Group: 'group'
}