export default {
    tested: '✔️',
    bug: '❌',
    Idea: '💡',
    Question: '❓',
    Important: '❗',
    Warning: '⚠️',
    stop_sign: '🛑',
    no_entry: '⛔',
    info: 'ℹ️',
    OK: '✔️',
    'not OK': '❌',
    'Priority 1': '1️⃣',
    'Priority 2': '2️⃣',
    'Priority 3': '3️⃣',
    'Priority 4': '4️⃣',
    'Priority 5': '5️⃣',
    'Priority 6': '6️⃣',
    'Priority 7': '7️⃣',
    'Priority 8': '8️⃣',
    'Priority 9': '9️⃣',
    'Priority 0': '0️⃣',
    'Red Traffic Light': '❤️',
    'Yellow Traffic Light': '💛',
    'Green Traffic Light': '💚',
    Back: '⬅️',
    Forward: '➡️',
    Up: '⬆️',
    Down: '⬇️',
    'Look here': '✏️',
    'I am happy': '🙂',
    'No Mind': '😐',
    'Surprising': '😮',
    'Angry': '😠',
    'I am not amused': '☹️',
    'Green Flag': '🏳',
    'Reg Flag': '🏴'
};