export default {
    tested: '✔️',
    bug: '❌',
    Idea: '💡',
    Question: '❓',
    Important: '❗',
    Warning: '⚠️',
    Stop: '🛑',
    'No Entry': '⛔',
    info: 'ℹ️',
    OK: '✔️',
    'Not OK': '❌',
    'Priority 1': '1️⃣',
    'Priority 2': '2️⃣',
    'Priority 3': '3️⃣',
    'Priority 4': '4️⃣',
    'Priority 5': '5️⃣',
    'Priority 6': '6️⃣',
    'Priority 7': '7️⃣',
    'Priority 8': '8️⃣',
    'Priority 9': '9️⃣',
    'Priority 0': '0️⃣',
    'Red Traffic Light': '❤️',
    'Yellow Traffic Light': '💛',
    'Green Traffic Light': '💚',
    Back: '⬅️',
    Forward: '➡️',
    Up: '⬆️',
    Down: '⬇️',
    'Look here': '✏️',
    'I am happy': '🙂',
    'No Mind': '😐',
    'Surprising': '😮',
    'Angry': '😠',
    'I am not amused': '☹️',
    'Dangerous': '💣',
    'Do not forget': '👜',
    'Home': '🏠',
    'Folder': '📁',
    'Mailbox': '📫',
    'Mail': '✉️',
    'E-Mail': '📧',
    'List': '🗒️',
    'Refine': '📝',
    'Phone': '📞',
    'Music': '🎵',
    'Key': '🔑',
    'To be refined': '✍️',
    'Magic': '✳️',
    'To be discussed': '🔍',
    'Remember': '🔔',
    'Excellent': '🌟',
    'Linux': '🐧',
    'Nice': '🌸',
    'FreeMind': '🦋',
    'Broken': '🔨',
    'Date': '📅',
    'Time': '🕓',
    'Waiting': '⏳',
    'Launch': '🚀',
    'Black Flag': '🖤',
    'Blue Flag': '💙',
    'Green Flag': '💚',
    'Orange Flag': '🧡',
    'Pink Flag': '💜',
    'Red Flag': '❤️',
    'Yellow Flag': '💛',
    'Family': '👪',
    'Female1': '👩',
    'Female2': '💃',
    'Male1': '👨',
    'Male2': '🕺',
    'Females': '👭',
    'Group': '👬',
};

export const SpecialIconsMap = {
    'Remove Last Icon': '⏮️',
    'Remove All Icons': '🗑',
    '': ''
};